# Generated by Django 2.1 on 2018-08-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day_of_the_week', models.CharField(choices=[('SU', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('SA', 'Saturday')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHoursSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('office_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_hours.OfficeHours')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('addressed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('office_hours_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_hours.OfficeHoursSession')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_hours.StudentQueue'),
        ),
        migrations.AddField(
            model_name='officehours',
            name='teaching_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office_hours.TeachingAssistant'),
        ),
    ]
